;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Findloople
DestinationPath=Content/Localization/Findloople
ManifestName=Findloople.manifest
ArchiveName=Findloople.archive
CulturesToGenerate=en
CulturesToGenerate=ja

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationReport
bWordCountReport=true
WordCountReportName=Findloople.csv

