;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Findloople
DestinationPath=Content/Localization/Findloople
ManifestName=Findloople.manifest
ArchiveName=Findloople.archive
ResourceName=Findloople.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=ja
CulturesToGenerate=en
CulturesToGenerate=ja

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

