;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Osagashi
DestinationPath=Content/Localization/Osagashi
ManifestName=Osagashi.manifest
ArchiveName=Osagashi.archive
ResourceName=Osagashi.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=ja
CulturesToGenerate=ja
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

