;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/OsagashiAdvance
DestinationPath=Content/Localization/OsagashiAdvance
ManifestName=OsagashiAdvance.manifest
ArchiveName=OsagashiAdvance.archive
ResourceName=OsagashiAdvance.locres
bSkipSourceCheck=false
bValidateFormatPatterns=true
bValidateSafeWhitespace=false
bValidateRichTextTags=false
NativeCulture=ja
CulturesToGenerate=ja
CulturesToGenerate=en

[GatherTextStep0]
CommandletClass=GenerateTextLocalizationResource

